# Generated by Django 3.1 on 2020-09-18 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_remove_place_information_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='native_speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_passport', models.FileField(upload_to='docs')),
                ('isAccepted', models.BooleanField(default=False)),
                ('org_1', models.CharField(max_length=100)),
                ('year_1', models.IntegerField()),
                ('type_1', models.CharField(max_length=100)),
                ('org_2', models.CharField(default=None, max_length=100, null=True)),
                ('year_2', models.IntegerField(default=None, null=True)),
                ('type_2', models.CharField(default=None, max_length=100, null=True)),
                ('org_3', models.CharField(default=None, max_length=100, null=True)),
                ('year_3', models.IntegerField(default=None, null=True)),
                ('type_3', models.CharField(default=None, max_length=100, null=True)),
                ('org_4', models.CharField(default=None, max_length=100, null=True)),
                ('year_4', models.IntegerField(default=None, null=True)),
                ('type_4', models.CharField(default=None, max_length=100, null=True)),
                ('which_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='place_information',
        ),
    ]
