# Generated by Django 3.1 on 2020-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200918_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='native_speaker',
            name='org_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='org_3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='org_4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='type_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='type_3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='type_4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='year_2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='year_3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='native_speaker',
            name='year_4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
