# Generated by Django 3.1 on 2020-10-06 07:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_auto_20200918_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(default=datetime.datetime(2020, 10, 6, 12, 15, 51, 332121))),
                ('text_type', models.CharField(max_length=30)),
                ('plane_text', models.TextField(blank=True, default=None, null=True)),
                ('attachment', models.FileField(blank=True, default=None, null=True, upload_to='work')),
                ('special_note', models.TextField(blank=True, default=None, null=True)),
                ('total_words', models.IntegerField(default=0)),
                ('file_type', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('alloted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.native_speaker')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
