# Generated by Django 3.1 on 2020-10-08 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20201008_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 0, 46, 26, 299796)),
        ),
        migrations.CreateModel(
            name='deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_file', models.FileField(upload_to='delivery')),
                ('order_date_time', models.DateTimeField(default=datetime.datetime(2020, 10, 9, 0, 46, 26, 299796))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.order')),
            ],
        ),
    ]
