# Generated by Django 3.1 on 2020-10-13 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0018_auto_20201009_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 15, 15, 47, 420639)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 15, 15, 47, 420639)),
        ),
        migrations.CreateModel(
            name='allMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('moment', models.DateTimeField(default=datetime.datetime(2020, 10, 13, 15, 15, 47, 420639))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
